#!/bin/bash

# CLIPSUM
# copy some lorem ipsum to clipboard
# use xclip
# -n arguement for no. of paragraphs

bold=$(tput bold)
normal=$(tput sgr0)

scriptName="$(basename $0)"
scriptPath="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"

# GET PATH OF SCRIPT, EVEN IF IS SYMLINK
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

p1="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent egestas finibus mauris eu gravida. Nunc convallis eget tellus a auctor. Nam ultricies ex ut nunc ultricies, eget porttitor est malesuada. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse nibh nunc, maximus eu sapien ac, convallis ultricies quam. Sed dictum lorem ut libero ornare, quis porta tellus pellentesque. Vivamus vitae feugiat metus. Proin eleifend congue sapien, at convallis neque. Sed dignissim euismod porttitor. Pellentesque molestie dictum tellus, vel pretium risus tincidunt sit amet."

p2="Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer cursus porttitor eros facilisis pretium. Curabitur tempor mi ac congue efficitur. Donec interdum justo vel turpis molestie, a finibus enim consequat. Proin pellentesque nisi vitae lectus iaculis condimentum. Nullam et lacus hendrerit, molestie turpis et, gravida ex. Fusce gravida, ipsum in pretium vulputate, velit lorem lacinia metus, ut vulputate erat nisl vitae justo. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pharetra est et nibh hendrerit, sit amet mollis arcu rhoncus. Cras porttitor pharetra mauris, consectetur fermentum augue pellentesque in. Suspendisse in viverra dolor. Proin nec felis enim. Mauris ut quam eu elit rutrum fermentum eu ut mauris. Suspendisse in cursus felis, ac tempor neque. Curabitur id molestie justo."

p3="Sed interdum id turpis at placerat. Quisque a enim et odio luctus tincidunt. Maecenas vel massa ligula. Quisque diam libero, dictum vel consequat vitae, pretium nec urna. Proin fermentum, orci vitae porta rutrum, massa sem facilisis sapien, vel suscipit est nunc quis odio. Duis egestas, orci ac tristique egestas, lectus ex finibus nibh, quis fermentum magna diam fermentum diam. Curabitur porttitor lorem quam, eget mollis purus varius pulvinar. Nunc euismod dictum nisl eget ultricies. Vestibulum aliquet eget odio sit amet iaculis. Curabitur blandit, dui sed vestibulum gravida, diam velit mattis massa, vel interdum metus ipsum ac odio. Donec egestas faucibus purus eu finibus. Vivamus pharetra congue neque, ut cursus arcu vestibulum a. Etiam blandit urna nec semper convallis."

p4="Ut pretium elit posuere ex laoreet, in fermentum quam ornare. Aliquam in volutpat massa, eget ultrices risus. Duis cursus erat facilisis aliquet consequat. Fusce at elit egestas, lacinia enim consectetur, vehicula velit. Pellentesque mollis nisi et velit placerat egestas. Nunc in auctor orci. Mauris id rutrum nibh, vel mattis velit. Integer sed tortor massa. Nullam et turpis urna. Aliquam eleifend diam vitae sem placerat faucibus. Nullam et tortor eu mi ullamcorper fermentum at nec velit. Maecenas porttitor, felis vel aliquet aliquet, mi neque fermentum erat, nec pretium risus magna quis est. Morbi scelerisque, magna id tincidunt efficitur, leo elit gravida magna, at eleifend arcu nisi a nulla. Vivamus venenatis dolor turpis."

p5="Etiam interdum vulputate facilisis. Pellentesque vel lobortis magna, eu dictum magna. Curabitur erat justo, rutrum vel feugiat eu, semper eget erat. Cras eget ornare velit. Phasellus vitae diam eget justo dignissim dignissim. Praesent sed rutrum justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam tempus magna vitae pulvinar malesuada. Proin sit amet euismod ipsum, a pharetra massa. Ut massa enim, laoreet facilisis ipsum id, luctus porta justo."

# CHECK IF XCLIP IS INSTALLED
if ! type xclip > /dev/null;
then
	
	printf "\033c"
	echo ">>${bold} ! please install xclip to use${normal}"
	

# SETUP
elif [[ $1 == "-setup" ]];
then

	sudo ln -sf $DIR/$scriptName /bin/$scriptName
	echo ">> ${bold}nice.${normal} made a symlink in /usr/bin. no bash prefix needed now"

elif [[ $1 == "-help" ]];
then
	
	echo "$ ${bold}clpsm -help${normal}        i think you already know this one.."
	echo "$ ${bold}clpsm -setup${normal}       run initial setup from clpsm/bash dir"
	echo "$ ${bold}clpsm${normal}              1 paragraph"
	echo "$ ${bold}clpsm -n 5${normal}         5 paragraphs"

# NUMBER ARGUEMENT
elif [[ $1 == "-n" ]];
then

	touch clpsm-temp

	for ((i=1; i <= $2; i++))
	do
		
		# > 5, LOOP BACK THROUGH VARS
		if (( "$i" > 5));
		then

			let mod="$i%5"
			pName="p$mod"

			# MODULUS 0 SHOULD BE 5
			if (( "$mod" == 0 ));
			then

				pName="p5"

			fi
		# 1-5 LOOP
		else

			pName="p$i" # MAKE VAR CALL FROM LOOP VAL

		fi

		echo "${!pName}" >> clpsm-temp
		echo \ >> clpsm-temp


	done

	xclip -sel c < clpsm-temp # COPY TO CLIPBOARD
	echo ">>  clpsm'd ${bold}$2 paragraphs${normal}. sikk"
	rm clpsm-temp # DEL TEMP FILE

# NO ARGUEMENT, DO 1 PARAGRAPH
else

	echo "$p1" > clpsm-temp
	xclip -sel c < clpsm-temp

	echo ">>  ${normal}clpsm'd ${bold}1 paragraph${normal}. yay"
	rm clpsm-temp
	
fi
